version: '3.8'

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ${COREDIR}/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro
    depends_on:
      - mqtt
    privileged: true

# Add this to configuration.yaml in HA
# recorder:
#  db_url: mysql://USERNAME:PASSWORD@mariadb/DBNAME?charset=utf8&unix_socket=/var/run/mysqld/mysqld.sock

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${SQLRPASS}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${SQLUSER}
      MYSQL_PASSWORD: ${SQLPASS}
    volumes:
      - ${COREDIR}/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

  binfmt:
    image: tonistiigi/binfmt
    privileged: true
    command: --install all
    restart: "no"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${COREDIR}/portainer_data:/data

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
